
# This file was *autogenerated* from the file functions.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4)
k = _sage_const_5 

# Use SR(), poly(x), polynomial(GF(k))
GF(k)['x']
g, h = GF(k)['g, h'].gens()
#var('x', domain='integer')
ga = x**_sage_const_4 *g + x**_sage_const_3 *h + x**_sage_const_2 *g + x*h + g
ha = x**_sage_const_4 *h + x**_sage_const_3 *g + x**_sage_const_3 *g + x**_sage_const_2 *h + x*g + x*g + h
#ha = x^4*h + 2*x^3*g + x^2*h + 2*x*g + h
var('z')

f0 = x**_sage_const_4 *g + x**_sage_const_3 *h + x**_sage_const_2 *g + x*h + g
f1 = x**_sage_const_4 *h + x**_sage_const_3 *g + x**_sage_const_3 *g + x**_sage_const_2 *h + x*g + x*g + h
f2 = (g + h)*x**_sage_const_4  + (_sage_const_2 *g + h)*x**_sage_const_3  + (g + h)*x**_sage_const_2  + (_sage_const_2 *g + h)*x + g + h
f3 = (g + _sage_const_2 *h)*x**_sage_const_4  + (_sage_const_4 *g + h)*x**_sage_const_3  + (g + _sage_const_2 *h)*x**_sage_const_2  + (_sage_const_4 *g + h)*x + g + _sage_const_2 *h
f4 = (g + _sage_const_3 *h)*x**_sage_const_4  + (g + h)*x**_sage_const_3  + (g + _sage_const_3 *h)*x**_sage_const_2  + (g + h)*x + g + _sage_const_3 *h
f5 = (g + _sage_const_4 *h)*x**_sage_const_4  + (_sage_const_3 *g + h)*x**_sage_const_3  + (g + _sage_const_4 *h)*x**_sage_const_2  + (_sage_const_3 *g + h)*x + g + _sage_const_4 *h

#f2 = (g + h)*x^4 + (g + g + h)*x^3 + (g + h)*x^2 + (g + g + h)*x + g + h
#f3 = (g + h + h)*x^4 + (g + g + g + g + h)*x^3 + (g + h + h)*x^2 + (g + g + g + g + h)*x + g + h + h
#f4 = (g + h + h + h)*x^4 + (g + h)*x^3 + (g + h + h + h)*x^2 + (g + h)*x + g + h + h + h
#f5 = (g + h + h + h + h)*x^4 + (g + g + g + h)*x^3 + (g + h + h + h + h)*x^2 + (g + g + g + h)*x + g + h + h + h + h
'''
def newF():
    #print("f0 = " + str(ga.expand().collect(x)))
    #print("f1 = " + str(ha.expand().collect(x)))
    for i in range(1,5):
        print("f{} = ".format(i+1) + str((ga + i*ha).expand().collect(x)))

def showPolynomials():
    for d in range(1):
        #var('y')
        #y = x + d
        print("d = {}".format(d))
        print("f0 = " + str(f0.expand().collect(x)))
        print("f1 = " + str(f1.expand().collect(x)))
        for i in range(1,k):
            print("f{} = ".format(i+1) + str((ga + i*ha).expand().collect(x)))
        print('')
'''

